# Generated by Django 5.2.13 on 2026-04-09 10:57

import django.db.models.deletion
import promoter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promoter', '0002_populate_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=70)),
                ('contact', models.CharField(validators=[promoter.validators.validate_phone])),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='promoter.promoter')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
