# Generated by Django 5.2.13 on 2026-04-12 21:23

import promoter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact',
            field=models.CharField(max_length=13, validators=[promoter.validators.validate_phone]),
        ),
    ]
